# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-0N_qdEAr0ON7WwH39VA9yAgv0BAtFv
"""

from google.colab import files

# upload a file
upload = files.upload()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
# %matplotlib inline

import seaborn as sns

from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

from sklearn.preprocessing import StandardScaler

from sklearn.cluster import KMeans

from sklearn.metrics import silhouette_samples, silhouette_score

bank_marketing_df = pd.read_csv('Bank_Marketing_Data.csv')
bank_marketing_df

bank_marketing_df.info()

bank_marketing_df.isna().sum()

sns.displot(x = 'spending', data = bank_marketing_df, kind = 'hist')
plt.grid()
plt.title('Distribution of the amount spent by the customer per month (in 1000s)')

sns.displot(x = 'advance_payments', data = bank_marketing_df, kind = 'hist')
plt.grid()
plt.title('Distribution of the amount paid by the customer in advance by cash (in 100s)')

sns.displot(x = 'probability_of_full_payment', data = bank_marketing_df, kind = 'hist')
plt.grid()
plt.title('Distribution of the probability of payment done in full by the customer to the bank')

sns.displot(x = 'current_balance', data = bank_marketing_df, kind = 'hist')
plt.grid()
plt.title('Distribution of balance amount left in the account of the customers to make purchases (in 1000s)')

sns.displot(x = 'credit_limit', data = bank_marketing_df, kind = 'hist')
plt.grid()
plt.title('Distribution of the limit of the amount in credit card (10000s)')

sns.displot(x = 'min_payment_amt', data = bank_marketing_df, kind = 'hist')
plt.grid()
plt.title('Distribution of the minimum amount paid by the customer while making payments for purchases made monthly (in 100s)')

sns.displot(x = 'max_spent_in_single_shopping', data = bank_marketing_df, kind = 'hist')
plt.grid()
plt.title('Maximum amount spent in one purchase (in 1000s) by the customer')

sns.pairplot(bank_marketing_df)

sns.boxplot(data = bank_marketing_df, orient = "h")
plt.title("Box plot for every feature in bank_marketing_df")

sns.heatmap(bank_marketing_df.corr(), annot = True)

wardlink = linkage(bank_marketing_df, method = 'ward')

dend = dendrogram(wardlink)
dend

dend = dendrogram(wardlink, truncate_mode = 'lastp', p = 10)
dend

#cluster = fcluster(wardlink, 2, criterion = 'maxclust')

ss = StandardScaler()

bank_marketing_scaled = ss.fit_transform(bank_marketing_df)
bank_marketing_scaled

wss = []

for i in range(1, bank_marketing_df.shape[1]+1):
  km = KMeans(n_clusters = i)
  km.fit(bank_marketing_scaled)
  wss.append(km.inertia_)

plt.figure(figsize = (10, 4))
plt.plot(range(1, bank_marketing_df.shape[1]+1), wss)
plt.grid()
plt.title("Within-Cluster Sum of Squares (WSS) plot for the each number of clusters")

km = KMeans(n_clusters = 2)
km.fit(bank_marketing_scaled)
labels = km.labels_
labels

sil_score = silhouette_score(bank_marketing_scaled, labels)
print('silhouette score for K-Means: ', sil_score)

sil_width = silhouette_samples(bank_marketing_scaled, labels)
bank_marketing_df['sil_width'] = sil_width

print("max of silhoutte_samples: ",silhouette_samples(bank_marketing_scaled, labels).max())
print("min of silhoutte_samples: ",silhouette_samples(bank_marketing_scaled, labels).min())

bank_marketing_df["cluster"] = labels
bank_marketing_df

sns.histplot(x = 'spending', data = bank_marketing_df, kde = True, hue = 'cluster')
plt.grid()
plt.title('Distribution of the amount spent by the customer per month (in 1000s)')

sns.histplot(x = 'advance_payments', data = bank_marketing_df, kde = True, hue = 'cluster')
plt.grid()
plt.title('Distribution of the amount paid by the customer in advance by cash (in 100s)')

sns.histplot(x = 'probability_of_full_payment', data = bank_marketing_df, kde = True, hue = 'cluster')
plt.grid()
plt.title('Distribution of the probability of payment done in full by the customer to the bank')

sns.histplot(x = 'current_balance', data = bank_marketing_df, kde = True, hue = 'cluster')
plt.grid()
plt.title('Distribution of balance amount left in the account of the customers to make purchases (in 1000s)')

sns.histplot(x = 'credit_limit', data = bank_marketing_df, kde = True, hue = 'cluster')
plt.grid()
plt.title('Distribution of the limit of the amount in credit card (10000s)')

sns.histplot(x = 'min_payment_amt', data = bank_marketing_df, kde = True, hue = 'cluster')
plt.grid()
plt.title('Distribution of the minimum amount paid by the customer while making payments for purchases made monthly (in 100s)')

sns.histplot(x = 'max_spent_in_single_shopping', data = bank_marketing_df, kde = True, hue = 'cluster')
plt.grid()
plt.title('Maximum amount spent in one purchase (in 1000s) by the customer')

